---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: kong-demo
servers: 1
agents: 3
# Optional set explicit K3s (Kubernetes) version
# image: rancher/k3s:v1.30.2-k3s2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8081:443
    nodeFilters:
      - loadbalancer
  - port: 44972:30001
    nodeFilters:
      - agents:*
  - port: 19000:9000/tcp
    nodeFilters:
      - agents:*
  - port: 19443:9443/tcp
    nodeFilters:
      - agents:*
registries:
  create:
    name: registry.example.com
    host: 0.0.0.0
    hostPort: "5002"
  config: |
    mirrors:
      rregistry.example.com:
        endpoint:
          - http://registry.example.com:5002
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - servers:*
