apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: kong
spec:
  type: kv-v2
  mount: kvv2
  path: kong/config
  destination:
    name: mysecretskv
    create: false
  refreshAfter: 30s
  vaultAuthRef: static-auth